packageExtensions:
  '@atls-ui-generators/icons@*':
    peerDependencies:
      glob: '^8.0.3'
  '@atls/config-jest@*':
    dependencies:
      jest: '^29.0.0'
      typescript: '*'


#   '@atls-ui-proto/theme@*':
#     dependencies:
#       react: '^17.0.1'

yarnPath: .yarn/releases/yarn-remote.cjs
