const lineHeights = {
  // atom: '',
  // tiny: '',
  // minor: '',
  // little: '',
  compact: '16px',
  // small: '',
  // tiddly: '',
  mini: '21px',
  // medium: '',
  // normal: '',
  standart: '27px',
  // ordinary: '',
  // regular: '',
  mean: '37px',
  // common: '',
  // larhe: '',
  huge: '64px',
  // big: '',
  giant: '75px',
  // enormous: '',
  // massive: '',
  // stupendous: '',
}

export { lineHeights }
